SELECT MAIN.ID_SUCURSAL, MAIN.ID_EMPLEADO, MAIN.NOMBRE_EMPLEADO, MAIN.ID_MESA, MAIN.PERIODO, MAIN.FECHA_ANTIGUEDAD, MAIN.FECHA_INGRESO_POSICION, MAIN.ESTATUS
FROM (
		SELECT 
		REF.GENERICATTRIBUTE1 ID_SUCURSAL,
		REF.NAME ID_EMPLEADO,
		REF.NOM NOMBRE_EMPLEADO,
		CASE
			WHEN REF.GENERICATTRIBUTE4 LIKE '%PAN_SURTIDO%' AND REF.ID_TIPO_MESA = 1 THEN 1
			WHEN REF.GENERICATTRIBUTE4 LIKE '%PASTELERO%' AND REF.ID_TIPO_MESA = 1 THEN 2
			WHEN REF.GENERICATTRIBUTE4 LIKE '%BIZCOCHERO%' AND REF.ID_TIPO_MESA = 2 THEN 3
			WHEN REF.GENERICATTRIBUTE4 LIKE '%FRANCESERO%' AND REF.ID_TIPO_MESA = 2 THEN 4
			WHEN REF.GENERICATTRIBUTE4 LIKE '%PASTELERO%' AND REF.ID_TIPO_MESA = 2 THEN 5
			ELSE 6
		END ID_MESA,
		PER.NAME PERIODO,
		REF.ANT FECHA_ANTIGUEDAD,
		REF.INGPOS FECHA_INGRESO_POSICION,
		CASE
			WHEN REF.FECHA_DESCANSO IS NULL THEN 'SIN DESCANSO'
		ELSE 'DESCANSO CAPTURADO'
		END ESTATUS
	FROM (
		SELECT A.GENERICATTRIBUTE1, A.NAME, P.FIRSTNAME|| ' ' ||P.MIDDLENAME NOM, A.GENERICATTRIBUTE4, TO_DATE(P.HIREDATE) ANT, TO_DATE(A.EFFECTIVESTARTDATE) INGPOS, B.ID_FEC_DESCANSO FECHA_DESCANSO, S.ID_TIPO_MESA
		FROM (
			SELECT GENERICATTRIBUTE1, NAME, EFFECTIVESTARTDATE, GENERICATTRIBUTE4
			FROM TCMP.CS_POSITION
			WHERE REMOVEDATE = '2200-01-01'
			AND ISLAST = 1
			AND PAYEESEQ IS NOT NULL
			AND GENERICATTRIBUTE1 IS NOT NULL
			AND TITLESEQ IN (
				SELECT RULEELEMENTOWNERSEQ
				FROM TCMP.CS_TITLE
				WHERE REMOVEDATE = '2200-01-01'
				AND (NAME LIKE '%PAN_SURTIDO%' OR NAME LIKE '%PASTELERO%' OR NAME LIKE '%BIZCOCHERO%' OR NAME LIKE '%FRANCESERO%')
			)
		) A -- PLANTILLA
		LEFT JOIN (
			SELECT ID_SUCURSAL, ID_NUM_EMPL, ID_FEC_DESCANSO
			FROM EXT.TB_DESCANSO_WKF
			WHERE ID_FEC_DESCANSO BETWEEN '2024-11-09' AND '2024-11-15' -- VARIABLE
		) B -- DESCANSO
		ON A.GENERICATTRIBUTE1 = TO_VARCHAR(B.ID_SUCURSAL)
		AND A.NAME = TO_VARCHAR(B.ID_NUM_EMPL)
		INNER JOIN TCMP.CS_PARTICIPANT P -- PARTICIPANT
		ON P.USERID = A.NAME
		AND REMOVEDATE = '2200-01-01'
		AND ISLAST = 1
		INNER JOIN EXT.TB_SUCURSAL_WKF S
		ON S.ID_SUCURSAL = A.GENERICATTRIBUTE1
	) REF, TCMP.CS_PERIOD PER
	WHERE STARTDATE = '2024-11-09' -- VARIABLE
	AND DESCRIPTION = 'SEM'
	AND REMOVEDATE = '2200-01-01'
) MAIN
WHERE MAIN.ESTATUS = 'SIN DESCANSO'