CREATE TRIGGER "EXT"."TG_SUCME_AI" AFTER INSERT ON "EXT"."TB_EMPLEADO_TEST" REFERENCING NEW ROW MYNEWROW FOR EACH ROW 
BEGIN       

	DECLARE id_tipo_mesa INT;
	DECLARE id_mesa INT;
	
	-- DELETE DUPLICATED
	DELETE FROM EXT.TB_SUCMESAEMPL_WKF HIS
	WHERE 1=1
	AND HIS.ID_SUCURSAL||HIS.ID_EMPLEADO IN (
    	SELECT HIS.ID_SUCURSAL||HIS.ID_EMPLEADO MEGA_LLAVE
    	FROM EXT.TB_EMPLEADO_TEST TEMP 
    	LEFT JOIN EXT.TB_SUCMESAEMPL_WKF HIS
		ON TEMP.GA1 = HIS.ID_SUCURSAL
    	AND TEMP.NAME = HIS.ID_EMPLEADO
    	WHERE 1 = 1
    	AND HIS.ID_SUCURSAL = :mynewrow.GA1
    	AND HIS.ID_EMPLEADO = :mynewrow.NAME
);
	
	SELECT CAR.ID_TIPO_MESA, CAR.ID_MESA
	INTO id_tipo_mesa, id_mesa
	FROM EXT.TB_CARGOS_WKF CAR
	INNER JOIN EXT.TB_SUCURSAL_WKF SUC
	ON CAR.ID_TIPO_MESA = SUC.ID_TIPO_MESA
	WHERE ID_CARGO = :mynewrow.GA3
	AND SUC.ID_SUCURSAL = :mynewrow.GA1;
	
	-- INSERT
	INSERT INTO EXT.TB_SUCMESAEMPL_WKF(ID_SUCURSAL, ID_EMPLEADO, ID_CVE_EMPRESA, ID_TIPO_MESA, ID_MESA, ID_CARGO, DESCRIPCION, FECHA_CREACION, FECHA_MODIFICACION, ESTATUS, USUARIO_CREACION, USUARIO_MODIFICACION)
	VALUES (TO_INT(:mynewrow.GA1), :mynewrow.NAME, 'S0004', :id_tipo_mesa, :id_mesa, :mynewrow.GA3, :mynewrow.DESC_CARGO, CURRENT_DATE, CURRENT_DATE, TRUE, 'SYSTEM', 'SYSTEM');
	
	-- DELETE
	DELETE FROM EXT.TB_SUCMESAEMPL_WKF HIS
	WHERE 1=1
	AND HIS.ID_SUCURSAL||HIS.ID_EMPLEADO IN (
    	SELECT HIS.ID_SUCURSAL||HIS.ID_EMPLEADO MEGA_LLAVE
    	FROM EXT.TB_EMPLEADO_TEST TEMP 
    	LEFT JOIN EXT.TB_SUCMESAEMPL_WKF HIS
		ON TEMP.GA1 = HIS.ID_SUCURSAL
    	AND TEMP.NAME = HIS.ID_EMPLEADO
    	WHERE 1 = 1
    	AND HIS.ID_SUCURSAL = :mynewrow.GA1
    	AND HIS.ID_EMPLEADO = :mynewrow.NAME
    	AND TEMP.PAYEE IS NULL
	);
END