CREATE OR REPLACE PROCEDURE EXT.PROC_TXN_ASSIGN_STAGEHOOK (IN pipelineRunSeq BIGINT)
LANGUAGE SQLSCRIPT
SQL SECURITY INVOKER
DEFAULT SCHEMA EXT
AS

BEGIN

	-- VARIABLES
	DECLARE lv_period_seq BIGINT;
	DECLARE lv_start_date DATE;
	DECLARE lv_dtype_venta BIGINT;
	DECLARE lv_dtype_produ BIGINT;
	DECLARE lv_dtype_trans BIGINT;
	DECLARE lv_dtype_merma BIGINT;
	DECLARE lv_dtype_produE BIGINT;
	DECLARE lv_punit BIGINT;
	-- EVENTO
	DECLARE lv_min_evento DATE;
	DECLARE lv_max_evento DATE;
	DECLARE lv_salestransactionseq BIGINT;
	DECLARE lv_sorder BIGINT;
	DECLARE lv_utype BIGINT;
	
	-- PERIODSEQ
	SELECT PERIODSEQ 
	INTO lv_period_seq DEFAULT NULL--2533274790398028
	FROM TCMP.CS_PlRUN
	WHERE PIPELINERUNSEQ = :pipelineRunSeq; 

	-- DATE
	SELECT STARTDATE 
	INTO lv_start_date DEFAULT NULL
	FROM TCMP.CS_PERIOD PER
	INNER JOIN TCMP.CS_PIPELINERUN PL
	ON PER.PERIODSEQ = PL.PERIODSEQ
	WHERE PL.PIPELINERUNSEQ = :pipelineRunSeq
	AND PER.REMOVEDATE = '2200-01-01 00:00:00.000000000';
	
	-- EVENTTYPE
	-- VENTAS DIARIAS
	SELECT DATATYPESEQ 
	INTO lv_dtype_venta DEFAULT NULL
	FROM TCMP.CS_EVENTTYPE
	WHERE EVENTTYPEID = 'VENTA DIARIA'
	AND REMOVEDATE = '2200-01-01 00:00:00.000000000';
	
	-- PRODUCCIÓN DIARIA
	SELECT DATATYPESEQ 
	INTO lv_dtype_produ DEFAULT NULL
	FROM TCMP.CS_EVENTTYPE
	WHERE EVENTTYPEID = 'PRODUCCION DIARIA'
	AND REMOVEDATE = '2200-01-01 00:00:00.000000000';
	
	-- TRANSFERENCIA DIARIA
	SELECT DATATYPESEQ 
	INTO lv_dtype_trans DEFAULT NULL
	FROM TCMP.CS_EVENTTYPE
	WHERE EVENTTYPEID = 'TRANSFERENCIA DIARIA'
	AND REMOVEDATE = '2200-01-01 00:00:00.000000000';
	
	-- MERMA
	SELECT DATATYPESEQ 
	INTO lv_dtype_merma DEFAULT NULL
	FROM TCMP.CS_EVENTTYPE
	WHERE EVENTTYPEID = 'MERMA'
	AND REMOVEDATE = '2200-01-01 00:00:00.000000000';
	
	-- INDICADORES EVENTO
	SELECT DATATYPESEQ 
	INTO lv_dtype_produE DEFAULT 123456789
	FROM TCMP.CS_EVENTTYPE
	WHERE EVENTTYPEID = 'INDICADORES DE EVENTO'
	AND REMOVEDATE = '2200-01-01 00:00:00.000000000';
	
	-- PROCESSING UNIT
	SELECT PROCESSINGUNITSEQ
	INTO lv_punit DEFAULT NULL
	FROM TCMP.CS_PROCESSINGUNIT
	WHERE NAME = 'PU_SORIANA_PANIFICADORA';
	
	-- SALESORDER EVENTO
	SELECT SALESORDERSEQ
	INTO lv_sorder DEFAULT 123456789
	FROM TCMP.CS_SALESORDER
	WHERE ORDERID = 'EVENTO';

	-- FECHA MIN EVENTO
	SELECT MIN(FEC_INI_PRODUCCION)
	INTO lv_min_evento DEFAULT '2024-01-04'
	FROM EXT.TB_EVENTO_WKF;
	-- WHERE ID_SUCURSAL = 661;
	
	-- FECHA MAX EVENTO
	SELECT MAX(FEC_FIN_VENTA)
	INTO lv_max_evento DEFAULT '2024-01-04'
	FROM EXT.TB_EVENTO_WKF;
	-- WHERE ID_SUCURSAL = 661;
	
	-- MESA | FACTOR
	UPDATE TCMP.CS_SALESTRANSACTION
	SET TCMP.CS_SALESTRANSACTION.GENERICATTRIBUTE1 = EXT.TB_PRODUCTOFACT_HIS.ID_MESA,
	TCMP.CS_SALESTRANSACTION.GENERICNUMBER3 = EXT.TB_PRODUCTOFACT_HIS.FACTOR
	FROM TCMP.CS_SALESTRANSACTION, EXT.TB_PRODUCTOFACT_HIS
	WHERE TCMP.CS_SALESTRANSACTION.LINENUMBER = EXT.TB_PRODUCTOFACT_HIS.ID_SUCURSAL
	AND TCMP.CS_SALESTRANSACTION.PRODUCTID = EXT.TB_PRODUCTOFACT_HIS.ID_PRODUCTO
	AND TCMP.CS_SALESTRANSACTION.COMPENSATIONDATE = :lv_start_date
	AND TCMP.CS_SALESTRANSACTION.EVENTTYPESEQ IN (:lv_dtype_venta, :lv_dtype_trans)  -- VENTA, TRANSFERENCIA
	AND TCMP.CS_SALESTRANSACTION.PROCESSINGUNITSEQ = :lv_punit; -- PANADERIA
	
	-- CREACION Y ASIGNACIÓN DE TXN DE EVENTO
	IF (:lv_start_date BETWEEN :lv_min_evento AND :lv_max_evento) THEN 
		-- ASIGNACIÓN CON EVENTO
		INSERT INTO EXT.TB_EVENTO_ADMIN
			SELECT :lv_start_date, 'LA FECHA ESTA DENTRO DE LOS PERIODOS DE EVENTO', CURRENT_TIMESTAMP
			FROM DUMMY;
		
		-- ***CREACION DE TXN***	
		DELETE FROM TCMP.CS_SALESTRANSACTION
		WHERE EVENTTYPESEQ = :lv_dtype_produE
		AND COMPENSATIONDATE = :lv_start_date; -- PRODUCCION POR EVENTO
		
		-- SALES TRANSACTION ID
		SELECT MAX(SALESTRANSACTIONSEQ)
		INTO lv_salestransactionseq DEFAULT NULL
		FROM TCMP.CS_SALESTRANSACTION;
		
		-- UNITTYPE
		SELECT UNITTYPESEQ
		INTO lv_utype DEFAULT NULL -- QUANTITY
		FROM TCMP.CS_UNITTYPE
		WHERE REMOVEDATE = '2200-01-01'
		AND NAME = 'quantity';
		
		-- INSERT DATOS EVENTO
		DELETE FROM EXT.TB_DATOS_EVENTO;
	
		INSERT INTO EXT.TB_DATOS_EVENTO
		SELECT 
			A.ID_SUCURSAL,
			A.ID_CVE_CODIGO,
			A.ID_NUM_MESATRABAJO,
			A.ID_FEC_PRODUCCION,
			A.NAME,
			A.UNIDADES_PRODUCIDAS,
			A.ACUMULADO_PRODUCIDAS,
			IFNULL(B.UNIDADES_VENDIDAS, 0) UNIDADES_VENDIDAS,
			IFNULL(B.ACUMULADO_VENDIDAS, 0) ACUMULADO_VENDIDAS,
			A.FACTOR,
			A.FEC_INI_PRODUCCION,
			A.FEC_FIN_VENTA,
			A.ACUMULADO_PRODUCIDAS, -- ACUM_DIARIO
			A.ID_FEC_PRODUCCION -- COMPENSATIN
		FROM (
				SELECT 
				PD.ID_SUCURSAL,
				PD.ID_CVE_CODIGO,
				PD.ID_NUM_MESATRABAJO,
				PD.ID_FEC_PRODUCCION,
				CL.NAME,
				PD.UNIDADES_PRODUCIDAS,
				SUM(UNIDADES_PRODUCIDAS) OVER (PARTITION BY PD.ID_SUCURSAL, PD.ID_CVE_CODIGO ORDER BY PD.ID_FEC_PRODUCCION) ACUMULADO_PRODUCIDAS,
				PF.FACTOR,
				E.FEC_INI_PRODUCCION,
				E.FEC_FIN_VENTA
			FROM EXT.TB_EVENTO_WKF E
			INNER JOIN EXT.TB_PRODUCCIONDIARIA_WKF PD
			ON E.ID_SUCURSAL = PD.ID_SUCURSAL
				AND E.ID_CVE_CODIGO = PD.ID_CVE_CODIGO
				AND E.ESTATUS = TRUE -- 13/01
				-- AND PD.ID_CVE_CODIGO = 7500525132024
				-- AND PD.ID_SUCURSAL = 2
				AND PD.ID_FEC_PRODUCCION BETWEEN E.FEC_INI_PRODUCCION AND E.FEC_FIN_PRODUCCION
				AND PD.ID_NUM_MESATRABAJO IN (1, 3) -- MESAS EVENTO
			-- ORDER BY PD.ID_FEC_PRODUCCION
			INNER JOIN EXT.TB_PRODUCTOFACT_HIS PF
			ON E.ID_SUCURSAL = PF.ID_SUCURSAL
				AND E.ID_CVE_CODIGO = PF.ID_PRODUCTO
				AND PF.FECHA_INICIO_VIGENCIA <= PD.ID_FEC_PRODUCCION
				AND PF.FECHA_FIN_VIGENCIA >= PD.ID_FEC_PRODUCCION
			INNER JOIN TCMP.CS_CLASSIFIER CL
			ON E.ID_CVE_CODIGO = CL.CLASSIFIERID
				AND CL.REMOVEDATE = '2200-01-01'
		) A
		FULL JOIN (
			SELECT 
				DD.LINENUMBER,
				DD.PRODUCTID,
				DD.COMPENSATIONDATE,
				DD.UNIDADES_VENDIDAS,
				SUM(DD.UNIDADES_VENDIDAS) OVER (PARTITION BY DD.LINENUMBER, DD.PRODUCTID ORDER BY DD.COMPENSATIONDATE) ACUMULADO_VENDIDAS
			FROM (
				SELECT 
				D.LINENUMBER,
				D.PRODUCTID,
				D.COMPENSATIONDATE,
				SUM(D.VALUE) UNIDADES_VENDIDAS
			FROM (
					SELECT 
					ST.LINENUMBER,
					ST.PRODUCTID,
					ST.COMPENSATIONDATE,
					ST.VALUE,
					SUM(ST.VALUE) OVER (PARTITION BY ST.LINENUMBER, ST.PRODUCTID, ST.COMPENSATIONDATE ORDER BY ST.COMPENSATIONDATE) ACUMULADO_VENDIDAS
				FROM EXT.TB_EVENTO_WKF E
				INNER JOIN TCMP.CS_SALESTRANSACTION ST
				ON E.ID_SUCURSAL = ST.LINENUMBER
					AND E.ID_CVE_CODIGO = ST.PRODUCTID
					AND E.ESTATUS = TRUE -- 13/01
					AND ST.COMPENSATIONDATE BETWEEN E.FEC_INI_VENTA AND E.FEC_FIN_VENTA
					AND (ST.EVENTTYPESEQ = :lv_dtype_venta -- VENTAS
					OR ST.EVENTTYPESEQ = :lv_dtype_trans) -- TRANS
			) D
			GROUP BY
				D.LINENUMBER,
				D.PRODUCTID,
				D.COMPENSATIONDATE
			) DD
		) B
		ON A.ID_SUCURSAL = B.LINENUMBER
			AND A.ID_CVE_CODIGO = B.PRODUCTID
			AND A.ID_FEC_PRODUCCION = B.COMPENSATIONDATE
		ORDER BY B.COMPENSATIONDATE;
		
		-- UPDATE TXN
		DELETE FROM EXT.TB_DATOS_TXN;
		
		INSERT INTO EXT.TB_DATOS_TXN
			SELECT *
			FROM EXT.TB_DATOS_EVENTO
			WHERE FECHA_PRODUCCION IS NOT NULL
			AND FECHA_PRODUCCION BETWEEN FECHA_PRODUCCION AND :lv_start_date
			AND ID_SUCURSAL IN (
				SELECT ID_SUCURSAL
				FROM (
					SELECT ID_SUCURSAL, MIN(FECHA_INI_EVENTO) INIE, MAX(FECHA_FIN_EVENTO) FINE
					FROM EXT.TB_DATOS_EVENTO
					-- WHERE ID_SUCURSAL IN (2, 661)
					GROUP BY ID_SUCURSAL
				) D
				WHERE D.INIE <= :lv_start_date
				AND :lv_start_date <= D.FINE
			);

		-- UPDATE PROD
		UPDATE DT
		SET DT.FECHA_PRODUCCION = :lv_start_date,
		DT.ACUMULADO_PRODUCIDAS = DE.ACUMULADO_PRODUCIDAS
		FROM EXT.TB_DATOS_TXN DT 
		INNER JOIN (
			SELECT 
				ID_SUCURSAL, 
				ID_PRODUCTO, 
				MAX(ACUMULADO_PRODUCIDAS) ACUMULADO_PRODUCIDAS, 
				MAX(FECHA_PRODUCCION) FECHA_PRODUCCION
			FROM EXT.TB_DATOS_EVENTO
			WHERE FECHA_PRODUCCION IS NOT NULL
			AND FECHA_PRODUCCION BETWEEN FECHA_PRODUCCION AND :lv_start_date
			GROUP BY ID_SUCURSAL, ID_PRODUCTO
		) DE
		ON DT.ID_SUCURSAL = DE.ID_SUCURSAL
		AND DT.ID_PRODUCTO = DE.ID_PRODUCTO;
		
		-- UPDATE VENTA
		UPDATE DT
		SET DT.UNIDADES_VENDIDAS = DE.UNIDADES_VENDIDAS,
		DT.ACUMULADO_VENDIDAS = DE.ACUMULADO_VENDIDAS
		FROM EXT.TB_DATOS_TXN DT 
		INNER JOIN (
			SELECT *
			FROM (
				SELECT 
					DD.LINENUMBER,
					DD.PRODUCTID,
					DD.COMPENSATIONDATE,
					DD.UNIDADES_VENDIDAS,
					SUM(DD.UNIDADES_VENDIDAS) OVER (PARTITION BY DD.LINENUMBER, DD.PRODUCTID ORDER BY DD.COMPENSATIONDATE) ACUMULADO_VENDIDAS
				FROM (
					SELECT 
					D.LINENUMBER,
					D.PRODUCTID,
					D.COMPENSATIONDATE,
					SUM(D.VALUE) UNIDADES_VENDIDAS
				FROM (
						SELECT 
						ST.LINENUMBER,
						ST.PRODUCTID,
						ST.COMPENSATIONDATE,
						ST.VALUE,
						SUM(ST.VALUE) OVER (PARTITION BY ST.LINENUMBER, ST.PRODUCTID, ST.COMPENSATIONDATE ORDER BY ST.COMPENSATIONDATE) ACUMULADO_VENDIDAS
					FROM EXT.TB_EVENTO_WKF E
					INNER JOIN TCMP.CS_SALESTRANSACTION ST
					ON E.ID_SUCURSAL = ST.LINENUMBER
						AND E.ID_CVE_CODIGO = ST.PRODUCTID
						AND E.ESTATUS = TRUE -- 13/01
						AND ST.COMPENSATIONDATE BETWEEN E.FEC_INI_VENTA AND E.FEC_FIN_VENTA
						AND (ST.EVENTTYPESEQ = :lv_dtype_venta -- VENTAS
						OR ST.EVENTTYPESEQ = :lv_dtype_trans) -- TRANS
				) D
				GROUP BY
					D.LINENUMBER,
					D.PRODUCTID,
					D.COMPENSATIONDATE
				) DD
			) C
			WHERE C.COMPENSATIONDATE = :lv_start_date
		) DE
		ON DT.ID_SUCURSAL = DE.LINENUMBER
		-- AND DT.FECHA_PRODUCCION = DE.COMPENSATIONDATE
		AND DT.ID_PRODUCTO = DE.PRODUCTID;
		
		-- INSERT INTO TCMP.CS_SALESTRANSACTION
		INSERT INTO TCMP.CS_SALESTRANSACTION (
		TENANTID, 
		SALESTRANSACTIONSEQ, 
		SALESORDERSEQ, 
		LINENUMBER, 
		SUBLINENUMBER, 
		EVENTTYPESEQ, 
		ORIGINTYPEID, 
		COMPENSATIONDATE,
		ISRUNNABLE,
		BUSINESSUNITMAP,
		PRODUCTID,
		PRODUCTNAME,
		PREADJUSTEDVALUE,
		UNITTYPEFORPREADJUSTEDVALUE,
		VALUE,
		UNITTYPEFORVALUE,
		GENERICATTRIBUTE1,
		GENERICATTRIBUTE3,
		-- GENERICATTRIBUTE5,
		GENERICNUMBER1,
		UNITTYPEFORGENERICNUMBER1,
		GENERICNUMBER2,
		UNITTYPEFORGENERICNUMBER2,
		GENERICNUMBER3,
		UNITTYPEFORGENERICNUMBER3,
		-- GENERICNUMBER4, -- ACUM DIARIO
		-- UNITTYPEFORGENERICNUMBER4, -- QUANTITY
		GENERICDATE1,
		GENERICDATE2,
		GENERICDATE3, -- COMPENSATION
		PROCESSINGUNITSEQ,
		MODIFICATIONDATE,
		MODELSEQ
	)
		SELECT 
			'G0FD', --TENANTID
			:lv_salestransactionseq + 10000000000000 + ROW_NUMBER() OVER (ORDER BY SO.SALESORDERSEQ) SALESTRANSACTIONSEQ,
			:lv_sorder, -- SALESORDERSEQ EVENTO
			C.ID_PRODUCTO||EXTRACT_DAY(C.COMPENSATION), -- LINENUMBER
			TO_BIGINT(TO_VARCHAR(C.FECHA_PRODUCCION, 'YYYYMMDD')), -- SUBLINENUMBER
			:lv_dtype_produE, -- PRODUCCION POR EVENTO -- EVENTTYEPSEQ
			'manual', -- ORIGINTYPEID
			TO_TIMESTAMP(C.FECHA_PRODUCCION), -- COMPENSATIONDATE
			1, -- ISRUNNABLE
			1, -- BUSINESSUNIT MAP
			C.ID_PRODUCTO, --PRODUCTID
			C.PRODUCTNAME, --PRODUCTNAME
			C.UNIDADES_PRODUCIDAS, -- PREADJUSTED
			:lv_utype, -- UNITTYPEPREADJUSTED QUANTITY
			C.UNIDADES_PRODUCIDAS, -- VALUE
			:lv_utype, -- UNITTYPEPERVALUE QUANTITY
			C.ID_MESA, -- GA1 MESA
			C.ID_SUCURSAL, --GA3 SUCURSAL
			-- C.FACTOR, -- GA5 FACTOR -- QUITAR ***
			C.ACUMULADO_PRODUCIDAS, -- GN1 -- ACUMUALDOS
			:lv_utype, -- UTFGN1
			C.ACUMULADO_VENDIDAS, -- GN2 UNIDADES VENDIDAS -- ACUMULADOS
			:lv_utype, -- UTFGN2 MXN
			C.FACTOR, -- GN3 factor
			:lv_utype, -- UTFGN3 -- QUANTITY
			-- C.ACUM_PROD_DIARIAS, -- GN4 -- quitar ***
			-- 1970324836974600, -- UTFGN4 -- quitar **
			C.FECHA_INI_EVENTO, -- GD1 INICIO EVENTO
			C.FECHA_FIN_EVENTO, -- GD2 FIN EVENTO
			C.COMPENSATION, -- COMPENSATION GD3
			:lv_punit, -- PU
			CURRENT_TIMESTAMP, -- MODIFICATIONDATE
			0 -- MODELSEQ
		FROM EXT.TB_DATOS_TXN C
		INNER JOIN TCMP.CS_SALESORDER SO
			ON C.ID_PRODUCTO = SO.ORDERID
			AND SO.REMOVEDATE = '2200-01-01'
			AND SO.PROCESSINGUNITSEQ = :lv_punit -- PU_SORIANA_PANIFICADORA
			AND C.FECHA_PRODUCCION IS NOT NULL;
		
		-- *** ASIGNACIÓN ***
		-- INSERCIÓN EN TCMP
		DELETE FROM TCMP.CS_TRANSACTIONASSIGNMENT 
		WHERE COMPENSATIONDATE = lv_start_date
		AND PROCESSINGUNITSEQ = :lv_punit; -- PANADERIA
		
		-- PROCESO NORMAL
		INSERT INTO TCMP.CS_TRANSACTIONASSIGNMENT (TENANTID, SALESTRANSACTIONSEQ, SETNUMBER, COMPENSATIONDATE, SALESORDERSEQ, POSITIONNAME, PROCESSINGUNITSEQ )
			-- VENTAS, PRODU, TRANS
			SELECT DISTINCT ST.TENANTID, ST.SALESTRANSACTIONSEQ, SUBSTRING (ST.SALESTRANSACTIONSEQ,11,8)||AST.ID_EMPLEADO AS SETNUMBER, ST.COMPENSATIONDATE, ST.SALESORDERSEQ, AST.ID_EMPLEADO, ST.PROCESSINGUNITSEQ
			FROM TCMP.CS_SALESTRANSACTION ST
			INNER JOIN EXT.TB_PRODUCTOFACT_HIS PF --MESA
			ON ST.LINENUMBER = PF.ID_SUCURSAL
			AND ST.PRODUCTID = TO_VARCHAR(PF.ID_PRODUCTO)
			INNER JOIN EXT.TB_ASISTENCIA_WKF AST -- EMPLEADO
			ON ST.LINENUMBER = AST.ID_SUCURSAL
			AND ST.COMPENSATIONDATE = AST.FECHA_ASISTENCIA
			AND PF.ID_MESA = AST.ID_MESA_REAL
			WHERE EVENTTYPESEQ IN (lv_dtype_venta, lv_dtype_produ, lv_dtype_trans) -- EVENTTYPE
			AND ESTATUS_TRANS IN ('0', '2', '4')
			AND ST.COMPENSATIONDATE = :lv_start_date -- STARTDATE
			AND AST.ASISTENCIA_ITX = TRUE
			AND AST.DECORADO IS NULL -- SIN EVENTO
			AND ST.PROCESSINGUNITSEQ = :lv_punit -- PANADERIA
			-- AND VALUE > 0 --VALIDATE ***COLOCAR LOS ESTATUS DE TRANS***
			OR (
				EVENTTYPESEQ IN (lv_dtype_venta, lv_dtype_produ, lv_dtype_trans) -- EVENTTYPE
				AND ESTATUS_TRANS IN (1, 3)
				AND ST.COMPENSATIONDATE = :lv_start_date -- STARTDATE
				AND AST.ASISTENCIA_ITX = FALSE
				AND AST.DECORADO = TRUE -- EVENTO
				AND ST.PROCESSINGUNITSEQ = :lv_punit -- PANADERIA
			)
			OR (
				EVENTTYPESEQ IN (lv_dtype_venta, lv_dtype_produ, lv_dtype_trans) -- EVENTTYPE
				AND ESTATUS_TRANS IN (2, 4)
				AND ST.COMPENSATIONDATE = :lv_start_date -- STARTDATE
				AND AST.ASISTENCIA_ITX = TRUE
				AND AST.DECORADO = FALSE -- EVENTO
				AND ST.PROCESSINGUNITSEQ = :lv_punit -- PANADERIA
			)
			UNION
			-- MERMA
			SELECT DISTINCT ST.TENANTID, ST.SALESTRANSACTIONSEQ, SUBSTRING (ST.SALESTRANSACTIONSEQ,11,8)||AST.ID_EMPLEADO AS SETNUMBER, ST.COMPENSATIONDATE, ST.SALESORDERSEQ, AST.ID_EMPLEADO, ST.PROCESSINGUNITSEQ
			FROM TCMP.CS_SALESTRANSACTION ST
			INNER JOIN EXT.TB_ASISTENCIA_WKF AST -- EMPLEADO
			ON ST.GENERICATTRIBUTE3 = TO_VARCHAR(AST.ID_SUCURSAL)
			WHERE ST.EVENTTYPESEQ = lv_dtype_merma -- EVENTTYPE
			AND ST.COMPENSATIONDATE BETWEEN ADD_DAYS(lv_start_date, -DAYOFMONTH(lv_start_date) + 1) AND LAST_DAY(lv_start_date) -- STARTDATE
			AND ST.COMPENSATIONDATE =  lv_start_date-- STARTDATE
			AND AST.FECHA_ASISTENCIA = lv_start_date -- STARTDATE
			AND AST.ASISTENCIA_ITX = TRUE
			AND ST.PROCESSINGUNITSEQ = :lv_punit -- PANADERIA
			UNION
			-- EXPRESS
			SELECT DISTINCT ST.TENANTID, ST.SALESTRANSACTIONSEQ, SUBSTRING (ST.SALESTRANSACTIONSEQ,11,8)||AST.ID_EMPLEADO AS SETNUMBER, ST.COMPENSATIONDATE, ST.SALESORDERSEQ, AST.ID_EMPLEADO, ST.PROCESSINGUNITSEQ
			FROM TCMP.CS_SALESTRANSACTION ST
			INNER JOIN EXT.TB_ASISTENCIA_WKF AST -- EMPLEADO
			ON ST.LINENUMBER = AST.ID_SUCURSAL
			AND ST.COMPENSATIONDATE = AST.FECHA_ASISTENCIA
			WHERE ST.EVENTTYPESEQ = lv_dtype_venta -- EVENTTYPE
			AND PRODUCTID IS NULL
			AND ST.COMPENSATIONDATE = lv_start_date -- STARTDATE
			AND AST.ASISTENCIA_ITX = TRUE
			AND ST.PROCESSINGUNITSEQ = :lv_punit -- PANADERIA
			UNION
			-- SECCION PRECIO
			SELECT DISTINCT ST.TENANTID, ST.SALESTRANSACTIONSEQ, SUBSTRING (ST.SALESTRANSACTIONSEQ,11,8)||AST.ID_EMPLEADO AS SETNUMBER, ST.COMPENSATIONDATE, ST.SALESORDERSEQ, AST.ID_EMPLEADO, ST.PROCESSINGUNITSEQ
			FROM TCMP.CS_SALESTRANSACTION ST
			INNER JOIN EXT.TB_ASISTENCIA_WKF AST -- EMPLEADO
			ON ST.LINENUMBER = AST.ID_SUCURSAL
			AND ST.COMPENSATIONDATE = AST.FECHA_ASISTENCIA
			WHERE EVENTTYPESEQ IN (lv_dtype_venta) -- EVENTTYPE
			AND ST.COMPENSATIONDATE = :lv_start_date
			AND ST.PRODUCTID = '9999999908026'
			AND ID_MESA_REAL IN (1, 3, 4)
			AND (AST.DECORADO IS NULL OR AST.DECORADO = FALSE) -- EVENTO
			AND ST.PROCESSINGUNITSEQ = :lv_punit -- PANADERIA
			AND AST.ASISTENCIA_ITX = TRUE;
		/*	
		-- VENTA NO REPARTIDA
		INSERT INTO TCMP.CS_TRANSACTIONASSIGNMENT (TENANTID, SALESTRANSACTIONSEQ, SETNUMBER, COMPENSATIONDATE, SALESORDERSEQ, POSITIONNAME, PROCESSINGUNITSEQ )
			-- VENTAS, PRODU, TRANS
			-- Puede haber problemas si el producto vive en ambas mesas
			SELECT DISTINCT ST.TENANTID, ST.SALESTRANSACTIONSEQ, SUBSTRING (ST.SALESTRANSACTIONSEQ,11,8)||AST.ID_EMPLEADO AS SETNUMBER, ST.COMPENSATIONDATE, ST.SALESORDERSEQ, AST.ID_EMPLEADO, ST.PROCESSINGUNITSEQ
			FROM TCMP.CS_SALESTRANSACTION ST
			INNER JOIN EXT.TB_PRODUCTOFACT_HIS PF --MESA
			ON ST.LINENUMBER = PF.ID_SUCURSAL
			AND ST.PRODUCTID = TO_VARCHAR(PF.ID_PRODUCTO)
			INNER JOIN EXT.TB_VENTANOREPARTIDA_WKF AST -- EMPLEADO
			ON ST.LINENUMBER = AST.ID_SUCURSAL
			AND ST.COMPENSATIONDATE = AST.FECHA_ASISTENCIA
			AND PF.ID_MESA = AST.ID_MESA
			WHERE EVENTTYPESEQ IN (lv_dtype_venta, lv_dtype_produ, lv_dtype_trans) -- EVENTTYPE
			AND ST.COMPENSATIONDATE = lv_start_date -- STARTDATE
			-- AND AST.ASISTENCIA_ITX = TRUE
			UNION
			-- SECCION PRECIO
			SELECT DISTINCT ST.TENANTID, ST.SALESTRANSACTIONSEQ, SUBSTRING (ST.SALESTRANSACTIONSEQ,11,8)||AST.ID_EMPLEADO AS SETNUMBER, ST.COMPENSATIONDATE, ST.SALESORDERSEQ, AST.ID_EMPLEADO, ST.PROCESSINGUNITSEQ
			FROM TCMP.CS_SALESTRANSACTION ST
			INNER JOIN EXT.TB_VENTANOREPARTIDA_WKF AST -- EMPLEADO
			ON ST.LINENUMBER = AST.ID_SUCURSAL
			AND ST.COMPENSATIONDATE = AST.FECHA_ASISTENCIA
			WHERE EVENTTYPESEQ IN (lv_dtype_venta) -- EVENTTYPE
			AND ST.COMPENSATIONDATE = :lv_start_date
			AND ST.PRODUCTID = '9999999908026'
			AND ID_MESA IN (1, 3, 4);
			-- AND AST.ASISTENCIA_ITX = TRUE;
		
		-- IDENTIFICADOR VENTAS
		UPDATE TCMP.CS_SALESTRANSACTION
		SET TCMP.CS_SALESTRANSACTION.GENERICBOOLEAN1 = 1
		FROM TCMP.CS_SALESTRANSACTION, (
			SELECT VNR.ID_SUCURSAL, VNR.ID_MESA, PF.ID_PRODUCTO, VNR.FECHA_ASISTENCIA 
			FROM EXT.TB_VENTANOREPARTIDA_WKF VNR
			INNER JOIN 
			EXT.TB_PRODUCTOFACT_HIS PF
			ON VNR.ID_SUCURSAL = PF.ID_SUCURSAL
				AND VNR.ID_MESA = PF.ID_MESA
		) MAINVNR
		WHERE TCMP.CS_SALESTRANSACTION.LINENUMBER = MAINVNR.ID_SUCURSAL
		AND TCMP.CS_SALESTRANSACTION.PRODUCTID = MAINVNR.ID_PRODUCTO
		AND TCMP.CS_SALESTRANSACTION.COMPENSATIONDATE = :lv_start_date
		AND TCMP.CS_SALESTRANSACTION.EVENTTYPESEQ IN (:lv_dtype_venta, :lv_dtype_trans);
		
		-- IDENTIFICADOR SECCION
		UPDATE TCMP.CS_SALESTRANSACTION
		SET GENERICBOOLEAN1 = 1
		FROM TCMP.CS_SALESTRANSACTION, EXT.TB_VENTANOREPARTIDA_WKF
		WHERE TCMP.CS_SALESTRANSACTION.LINENUMBER = EXT.TB_VENTANOREPARTIDA_WKF.ID_SUCURSAL
		AND TCMP.CS_SALESTRANSACTION.PRODUCTID = '9999999908026'
		AND TCMP.CS_SALESTRANSACTION.COMPENSATIONDATE = :lv_start_date
		AND EXT.TB_VENTANOREPARTIDA_WKF.ID_MESA IN (1, 3, 4);
		*/
		
		-- NATIVOS (SOBRE ASISTENCIA_WKF, ESTATUS O Y SIN APOYO)
		INSERT INTO TCMP.CS_TRANSACTIONASSIGNMENT (TENANTID, SALESTRANSACTIONSEQ, SETNUMBER, COMPENSATIONDATE, SALESORDERSEQ, POSITIONNAME, PROCESSINGUNITSEQ, GENERICDATE3, GENERICATTRIBUTE1, GENERICATTRIBUTE2, GENERICBOOLEAN1 )
			SELECT DISTINCT ST.TENANTID, ST.SALESTRANSACTIONSEQ, SUBSTRING (ST.SALESTRANSACTIONSEQ,11,8)||AST.ID_EMPLEADO AS SETNUMBER, ST.COMPENSATIONDATE, ST.SALESORDERSEQ, AST.ID_EMPLEADO, ST.PROCESSINGUNITSEQ, ST.GENERICDATE3, TO_VARCHAR(:lv_dtype_produE), AST.ESTATUS_TRANS, 0
				FROM TCMP.CS_SALESTRANSACTION ST
				INNER JOIN EXT.TB_ASISTENCIA_WKF AST -- EMPLEADO
				ON ST.GENERICATTRIBUTE3 = TO_VARCHAR(AST.ID_SUCURSAL)
				AND ST.COMPENSATIONDATE = AST.FECHA_ASISTENCIA -- COMPENSATION
				AND ST.GENERICATTRIBUTE1 = AST.ID_MESA_REAL
				WHERE ST.EVENTTYPESEQ = :lv_dtype_produE -- EVENTTYPE -- INDICADORESPOREVENTO
				AND ST.COMPENSATIONDATE = :lv_start_date -- STARTDATE
				AND AST.ID_EMPLEADO NOT LIKE '%C%'
				AND AST.ESTATUS_TRANS IN ('0')
				AND AST.DECORADO IS NULL
				AND AST.ID_SUCURSAL NOT IN (
					SELECT DISTINCT ID_SUCURSAL
					FROM EXT.TB_ASISTENCIA_EVENTO_WKF
					WHERE FECHA_ASISTENCIA = :lv_start_date
				)
				-- AND AST.ASISTENCIA_ITX = TRUE 22/01
				AND ST.PROCESSINGUNITSEQ = :lv_punit;
				
		-- CON APOYO (SOBRE ASISTENCIA_EVENTO Y TODOS LOS ESTATUS)
		-- EVENTO '0'
		INSERT INTO TCMP.CS_TRANSACTIONASSIGNMENT (TENANTID, SALESTRANSACTIONSEQ, SETNUMBER, COMPENSATIONDATE, SALESORDERSEQ, POSITIONNAME, PROCESSINGUNITSEQ, GENERICDATE3, GENERICATTRIBUTE1, GENERICATTRIBUTE2, GENERICBOOLEAN1 )
			SELECT DISTINCT ST.TENANTID, ST.SALESTRANSACTIONSEQ, SUBSTRING (ST.SALESTRANSACTIONSEQ,11,8)||AST.ID_EMPLEADO AS SETNUMBER, ST.COMPENSATIONDATE, ST.SALESORDERSEQ, AST.ID_EMPLEADO, ST.PROCESSINGUNITSEQ, ST.GENERICDATE3, TO_VARCHAR(:lv_dtype_produE), AST.ESTATUS_TRANS, 0
				FROM TCMP.CS_SALESTRANSACTION ST
				INNER JOIN EXT.TB_ASISTENCIA_EVENTO_WKF AST -- EMPLEADO
				ON ST.GENERICATTRIBUTE3 = TO_VARCHAR(AST.ID_SUCURSAL)
				AND ST.COMPENSATIONDATE = AST.FECHA_ASISTENCIA -- COMPENSATION
				AND ST.GENERICATTRIBUTE1 = AST.ID_MESA_REAL
				WHERE ST.EVENTTYPESEQ = :lv_dtype_produE -- EVENTTYPE -- INDICADORESPOREVENTO
				AND ST.COMPENSATIONDATE = :lv_start_date -- STARTDATE
				AND AST.ID_EMPLEADO NOT LIKE '%C%'
				AND AST.ESTATUS_TRANS IN ('0', '1', '3')
				AND AST.ID_MESA_REAL IN (1, 3)
				-- AND (AST.DECORADO = FALSE OR AST.DECORADO IS NULL)
				-- AND AST.ASISTENCIA_ITX = TRUE 22/01
				AND ST.PROCESSINGUNITSEQ = :lv_punit;
		
		-- EVENTO '2' AND '4' SIN CHECK 
		INSERT INTO TCMP.CS_TRANSACTIONASSIGNMENT (TENANTID, SALESTRANSACTIONSEQ, SETNUMBER, COMPENSATIONDATE, SALESORDERSEQ, POSITIONNAME, PROCESSINGUNITSEQ, GENERICDATE3, GENERICATTRIBUTE1, GENERICATTRIBUTE2, GENERICBOOLEAN1 )
			SELECT DISTINCT ST.TENANTID, ST.SALESTRANSACTIONSEQ, SUBSTRING (ST.SALESTRANSACTIONSEQ,11,8)||AST.ID_EMPLEADO AS SETNUMBER, ST.COMPENSATIONDATE, ST.SALESORDERSEQ, AST.ID_EMPLEADO, ST.PROCESSINGUNITSEQ, ST.GENERICDATE3, TO_VARCHAR(:lv_dtype_produE), AST.ESTATUS_TRANS, 1
				FROM TCMP.CS_SALESTRANSACTION ST
				INNER JOIN EXT.TB_ASISTENCIA_EVENTO_WKF AST -- EMPLEADO
				ON ST.GENERICATTRIBUTE3 = TO_VARCHAR(AST.ID_SUCURSAL)
				AND ST.GENERICDATE3 = AST.FECHA_ASISTENCIA -- COMPENSATION
				AND ST.GENERICATTRIBUTE1 = AST.ID_MESA_REAL
				WHERE ST.EVENTTYPESEQ = :lv_dtype_produE -- EVENTTYPE -- INDICADORESPOREVENTO
				AND AST.ID_EMPLEADO NOT LIKE '%C%'
				AND ST.COMPENSATIONDATE = :lv_start_date
				-- AND (AST.DECORADO = FALSE OR AST.DECORADO IS NULL)
				-- AND AST.ASISTENCIA_ITX = TRUE 22/01
				AND AST.ID_MESA_REAL IN (1, 3)
				AND AST.ESTATUS_TRANS IN ('2', '4')
				AND ST.PROCESSINGUNITSEQ = :lv_punit;
		
		-- ASIGNACIÓN
		-- NATIVOS (SOBRE ASISTENCIA_WKF, ESTATUS O Y SIN APOYO)
		UPDATE TA
		SET TA.GENERICNUMBER1 = AST.PORCENTAJE_PARTICIPACION_EMPLEADO / 100,
		TA.GENERICNUMBER2 = AST.ASISTENCIA_ITX
		FROM TCMP.CS_TRANSACTIONASSIGNMENT TA
		INNER JOIN (
			SELECT 
				ID_EMPLEADO,
				CASE 
					WHEN ASISTENCIA_ITX = TRUE THEN 1
					ELSE 0
				END ASISTENCIA_ITX,
				PORCENTAJE_PARTICIPACION_EMPLEADO,
				FECHA_ASISTENCIA
			FROM EXT.TB_ASISTENCIA_WKF
			-- WHERE FECHA_ASISTENCIA = :lv_start_date
			WHERE ESTATUS_TRANS IN ('0')
			-- AND ID_SUCURSAL NOT IN (
				-- SELECT DISTINCT ID_SUCURSAL
				-- FROM EXT.TB_ASISTENCIA_EVENTO_WKF
				-- WHERE FECHA_ASISTENCIA = :lv_start_date -- 23/01
			--)
			AND ID_EMPLEADO NOT LIKE '%C%'
		) AST
		ON TA.POSITIONNAME = AST.ID_EMPLEADO
		AND TA.GENERICDATE3 = AST.FECHA_ASISTENCIA
        AND TA.GENERICATTRIBUTE2 IN ('0')
		AND TA.GENERICATTRIBUTE1 = TO_VARCHAR(:lv_dtype_produE);
		-- AND TA.COMPENSATIONDATE = :lv_start_date;
		
		-- CON APOYO (SOBRE ASISTENCIA_EVENTO Y TODOS LOS ESTATUS)
		-- ASSIGN ASISTENCIA_ITX AND % PARTICIPACION TO TRANSACTION ASSIGNMENT '0', '1', '3' CON CHECK SOBRE ASITENCIA EVENTO
		UPDATE TA
		SET TA.GENERICNUMBER1 = AST.PORCENTAJE_PARTICIPACION_EMPLEADO / 100,
		TA.GENERICNUMBER2 = AST.ASISTENCIA_ITX
		FROM TCMP.CS_TRANSACTIONASSIGNMENT TA
		INNER JOIN (
			SELECT 
				ID_EMPLEADO,
				CASE 
					WHEN ASISTENCIA_ITX = TRUE THEN 1
					ELSE 0
				END ASISTENCIA_ITX,
				PORCENTAJE_PARTICIPACION_EMPLEADO,
				FECHA_ASISTENCIA
			FROM EXT.TB_ASISTENCIA_EVENTO_WKF
			-- WHERE FECHA_ASISTENCIA = :lv_start_date
			WHERE ESTATUS_TRANS IN ('0', '1', '3')
			AND ID_MESA_REAL IN (1, 3)
			AND ID_EMPLEADO NOT LIKE '%C%'
		) AST
		ON TA.POSITIONNAME = AST.ID_EMPLEADO
		AND TA.GENERICDATE3 = AST.FECHA_ASISTENCIA
        AND TA.GENERICATTRIBUTE2 IN ('0', '1', '3')
		AND TA.GENERICATTRIBUTE1 = TO_VARCHAR(:lv_dtype_produE);
		
		-- ASSIGN ASISTENCIA_ITX AND % PARTICIPACION TO TRANSACTION ASSIGNMENT '2', '4' CON CHECK SOBRE ASISTENCIA EVENTO
		UPDATE TA
		SET TA.GENERICNUMBER1 = AST.PORCENTAJE_PARTICIPACION_EMPLEADO / 100,
		TA.GENERICNUMBER2 = AST.ASISTENCIA_ITX
		FROM TCMP.CS_TRANSACTIONASSIGNMENT TA
		INNER JOIN (
			SELECT 
				ID_EMPLEADO,
				CASE 
					WHEN ASISTENCIA_ITX = TRUE THEN 1
					ELSE 0
				END ASISTENCIA_ITX,
				PORCENTAJE_PARTICIPACION_EMPLEADO,
				FECHA_ASISTENCIA
			FROM EXT.TB_ASISTENCIA_EVENTO_WKF
			-- WHERE FECHA_ASISTENCIA = :lv_start_date
			WHERE ESTATUS_TRANS IN ('2', '4')
			AND ID_MESA_REAL IN (1, 3)
			AND ID_EMPLEADO NOT LIKE '%C%'
		) AST
		ON TA.POSITIONNAME = AST.ID_EMPLEADO
		AND TA.GENERICDATE3 = AST.FECHA_ASISTENCIA
        AND TA.GENERICATTRIBUTE2 IN ('2', '4')
		AND TA.GENERICATTRIBUTE1 = TO_VARCHAR(:lv_dtype_produE);
		
		COMMIT;
	ELSE 
		-- ASIGNACIÓN SIN EVENTO
		INSERT INTO EXT.TB_EVENTO_ADMIN
			SELECT :lv_start_date, 'LA FECHA NO ESTA DENTRO DE LOS PERIODOS DE EVENTO', CURRENT_TIMESTAMP
			FROM DUMMY;
			
		-- INSERCIÓN EN TCMP
		DELETE FROM TCMP.CS_TRANSACTIONASSIGNMENT 
		WHERE COMPENSATIONDATE = lv_start_date
		AND PROCESSINGUNITSEQ = :lv_punit; -- PANADERIA
	
		-- PROCESO NORMAL
		INSERT INTO TCMP.CS_TRANSACTIONASSIGNMENT (TENANTID, SALESTRANSACTIONSEQ, SETNUMBER, COMPENSATIONDATE, SALESORDERSEQ, POSITIONNAME, PROCESSINGUNITSEQ )
			-- VENTAS, PRODU, TRANS
			SELECT DISTINCT ST.TENANTID, ST.SALESTRANSACTIONSEQ, SUBSTRING (ST.SALESTRANSACTIONSEQ,11,8)||AST.ID_EMPLEADO AS SETNUMBER, ST.COMPENSATIONDATE, ST.SALESORDERSEQ, AST.ID_EMPLEADO, ST.PROCESSINGUNITSEQ
			FROM TCMP.CS_SALESTRANSACTION ST
			INNER JOIN EXT.TB_PRODUCTOFACT_HIS PF --MESA
			ON ST.LINENUMBER = PF.ID_SUCURSAL
			AND ST.PRODUCTID = TO_VARCHAR(PF.ID_PRODUCTO)
			INNER JOIN EXT.TB_ASISTENCIA_WKF AST -- EMPLEADO
			ON ST.LINENUMBER = AST.ID_SUCURSAL
			AND ST.COMPENSATIONDATE = AST.FECHA_ASISTENCIA
			AND PF.ID_MESA = AST.ID_MESA_REAL
			WHERE EVENTTYPESEQ IN (lv_dtype_venta, lv_dtype_produ, lv_dtype_trans) -- EVENTTYPE
			AND ST.COMPENSATIONDATE = lv_start_date -- STARTDATE
			AND AST.ASISTENCIA_ITX = TRUE
			AND ST.PROCESSINGUNITSEQ = :lv_punit -- PANADERIA
			-- AND VALUE > 0 --VALIDATE ***COLOCAR LOS ESTATUS DE TRANS***
			UNION
			-- MERMA
			SELECT DISTINCT ST.TENANTID, ST.SALESTRANSACTIONSEQ, SUBSTRING (ST.SALESTRANSACTIONSEQ,11,8)||AST.ID_EMPLEADO AS SETNUMBER, ST.COMPENSATIONDATE, ST.SALESORDERSEQ, AST.ID_EMPLEADO, ST.PROCESSINGUNITSEQ
			FROM TCMP.CS_SALESTRANSACTION ST
			INNER JOIN EXT.TB_ASISTENCIA_WKF AST -- EMPLEADO
			ON ST.GENERICATTRIBUTE3 = TO_VARCHAR(AST.ID_SUCURSAL)
			WHERE ST.EVENTTYPESEQ = lv_dtype_merma -- EVENTTYPE
			AND ST.COMPENSATIONDATE BETWEEN ADD_DAYS(lv_start_date, -DAYOFMONTH(lv_start_date) + 1) AND LAST_DAY(lv_start_date) -- STARTDATE
			AND ST.COMPENSATIONDATE =  lv_start_date-- STARTDATE
			AND AST.FECHA_ASISTENCIA = lv_start_date -- STARTDATE
			AND AST.ASISTENCIA_ITX = TRUE
			AND ST.PROCESSINGUNITSEQ = :lv_punit -- PANADERIA
			UNION
			-- EXPRESS
			SELECT DISTINCT ST.TENANTID, ST.SALESTRANSACTIONSEQ, SUBSTRING (ST.SALESTRANSACTIONSEQ,11,8)||AST.ID_EMPLEADO AS SETNUMBER, ST.COMPENSATIONDATE, ST.SALESORDERSEQ, AST.ID_EMPLEADO, ST.PROCESSINGUNITSEQ
			FROM TCMP.CS_SALESTRANSACTION ST
			INNER JOIN EXT.TB_ASISTENCIA_WKF AST -- EMPLEADO
			ON ST.LINENUMBER = AST.ID_SUCURSAL
			AND ST.COMPENSATIONDATE = AST.FECHA_ASISTENCIA
			WHERE ST.EVENTTYPESEQ = lv_dtype_venta -- EVENTTYPE
			AND PRODUCTID IS NULL
			AND ST.COMPENSATIONDATE = lv_start_date -- STARTDATE
			AND AST.ASISTENCIA_ITX = TRUE
			AND ST.PROCESSINGUNITSEQ = :lv_punit -- PANADERIA
			UNION
			-- SECCION PRECIO
			SELECT DISTINCT ST.TENANTID, ST.SALESTRANSACTIONSEQ, SUBSTRING (ST.SALESTRANSACTIONSEQ,11,8)||AST.ID_EMPLEADO AS SETNUMBER, ST.COMPENSATIONDATE, ST.SALESORDERSEQ, AST.ID_EMPLEADO, ST.PROCESSINGUNITSEQ
			FROM TCMP.CS_SALESTRANSACTION ST
			INNER JOIN EXT.TB_ASISTENCIA_WKF AST -- EMPLEADO
			ON ST.LINENUMBER = AST.ID_SUCURSAL
			AND ST.COMPENSATIONDATE = AST.FECHA_ASISTENCIA
			WHERE EVENTTYPESEQ IN (lv_dtype_venta) -- EVENTTYPE
			AND ST.COMPENSATIONDATE = :lv_start_date
			AND ST.PRODUCTID = '9999999908026'
			AND ID_MESA_REAL IN (1, 3, 4)
			AND ST.PROCESSINGUNITSEQ = :lv_punit -- PANADERIA
			AND AST.ASISTENCIA_ITX = TRUE;
		/*	
		-- VENTA NO REPARTIDA
		INSERT INTO TCMP.CS_TRANSACTIONASSIGNMENT (TENANTID, SALESTRANSACTIONSEQ, SETNUMBER, COMPENSATIONDATE, SALESORDERSEQ, POSITIONNAME, PROCESSINGUNITSEQ )
			-- VENTAS, PRODU, TRANS
			-- Puede haber problemas si el producto vive en ambas mesas
			SELECT DISTINCT ST.TENANTID, ST.SALESTRANSACTIONSEQ, SUBSTRING (ST.SALESTRANSACTIONSEQ,11,8)||AST.ID_EMPLEADO AS SETNUMBER, ST.COMPENSATIONDATE, ST.SALESORDERSEQ, AST.ID_EMPLEADO, ST.PROCESSINGUNITSEQ
			FROM TCMP.CS_SALESTRANSACTION ST
			INNER JOIN EXT.TB_PRODUCTOFACT_HIS PF --MESA
			ON ST.LINENUMBER = PF.ID_SUCURSAL
			AND ST.PRODUCTID = TO_VARCHAR(PF.ID_PRODUCTO)
			INNER JOIN EXT.TB_VENTANOREPARTIDA_WKF AST -- EMPLEADO
			ON ST.LINENUMBER = AST.ID_SUCURSAL
			AND ST.COMPENSATIONDATE = AST.FECHA_ASISTENCIA
			AND PF.ID_MESA = AST.ID_MESA
			WHERE EVENTTYPESEQ IN (lv_dtype_venta, lv_dtype_produ, lv_dtype_trans) -- EVENTTYPE
			AND ST.COMPENSATIONDATE = lv_start_date -- STARTDATE
			-- AND AST.ASISTENCIA_ITX = TRUE
			UNION
			-- SECCION PRECIO
			SELECT DISTINCT ST.TENANTID, ST.SALESTRANSACTIONSEQ, SUBSTRING (ST.SALESTRANSACTIONSEQ,11,8)||AST.ID_EMPLEADO AS SETNUMBER, ST.COMPENSATIONDATE, ST.SALESORDERSEQ, AST.ID_EMPLEADO, ST.PROCESSINGUNITSEQ
			FROM TCMP.CS_SALESTRANSACTION ST
			INNER JOIN EXT.TB_VENTANOREPARTIDA_WKF AST -- EMPLEADO
			ON ST.LINENUMBER = AST.ID_SUCURSAL
			AND ST.COMPENSATIONDATE = AST.FECHA_ASISTENCIA
			WHERE EVENTTYPESEQ IN (lv_dtype_venta) -- EVENTTYPE
			AND ST.COMPENSATIONDATE = :lv_start_date
			AND ST.PRODUCTID = '9999999908026'
			AND ID_MESA IN (1, 3, 4);
			-- AND AST.ASISTENCIA_ITX = TRUE;
		
		-- IDENTIFICADOR VENTAS
		UPDATE TCMP.CS_SALESTRANSACTION
		SET TCMP.CS_SALESTRANSACTION.GENERICBOOLEAN1 = 1
		FROM TCMP.CS_SALESTRANSACTION, (
			SELECT VNR.ID_SUCURSAL, VNR.ID_MESA, PF.ID_PRODUCTO, VNR.FECHA_ASISTENCIA 
			FROM EXT.TB_VENTANOREPARTIDA_WKF VNR
			INNER JOIN 
			EXT.TB_PRODUCTOFACT_HIS PF
			ON VNR.ID_SUCURSAL = PF.ID_SUCURSAL
				AND VNR.ID_MESA = PF.ID_MESA
		) MAINVNR
		WHERE TCMP.CS_SALESTRANSACTION.LINENUMBER = MAINVNR.ID_SUCURSAL
		AND TCMP.CS_SALESTRANSACTION.PRODUCTID = MAINVNR.ID_PRODUCTO
		AND TCMP.CS_SALESTRANSACTION.COMPENSATIONDATE = :lv_start_date
		AND TCMP.CS_SALESTRANSACTION.EVENTTYPESEQ IN (:lv_dtype_venta, :lv_dtype_trans);
		
		-- IDENTIFICADOR SECCION
		UPDATE TCMP.CS_SALESTRANSACTION
		SET GENERICBOOLEAN1 = 1
		FROM TCMP.CS_SALESTRANSACTION, EXT.TB_VENTANOREPARTIDA_WKF
		WHERE TCMP.CS_SALESTRANSACTION.LINENUMBER = EXT.TB_VENTANOREPARTIDA_WKF.ID_SUCURSAL
		AND TCMP.CS_SALESTRANSACTION.PRODUCTID = '9999999908026'
		AND TCMP.CS_SALESTRANSACTION.COMPENSATIONDATE = :lv_start_date
		AND EXT.TB_VENTANOREPARTIDA_WKF.ID_MESA IN (1, 3, 4);
		*/
	
		COMMIT;
	
	END IF;
END