CREATE PROCEDURE EXT.SP_ASTNC (In FILENAME VARCHAR(255))
LANGUAGE SQLSCRIPT
SQL SECURITY INVOKER
DEFAULT SCHEMA EXT
AS
BEGIN
 
--DELETE
 
DELETE FROM EXT.TB_ASISTENCIA_ITX_HIS HIS
WHERE 1=1
AND HIS.ID_SUCURSAL||HIS.ID_EMPLEADO||HIS.FECHA_LECTURA||HIS.TIPO_LECTURA||HIS.TURNO IN (
    SELECT HIS.ID_SUCURSAL||HIS.ID_EMPLEADO||HIS.FECHA_LECTURA||HIS.TIPO_LECTURA||HIS.TURNO MEGA_LLAVE
    FROM EXT.TB_ASISTENCIA_ITX_TMP TEMP 
    LEFT JOIN EXT.TB_ASISTENCIA_ITX_HIS HIS
    ON TEMP.ID_SUCURSAL = HIS.ID_SUCURSAL
    AND TEMP.ID_EMPLEADO = HIS.ID_EMPLEADO
    AND TO_DATE(TEMP.FECHA_LECTURA, 'MM/DD/YYYY') = HIS.FECHA_LECTURA
    AND TEMP.TIPO_LECTURA = HIS.TIPO_LECTURA
    AND TEMP.TURNO = HIS.TURNO
    WHERE 1=1
    AND TEMP.ACCION = 'INSERTAR'
);
 
-- Insert into HIS
INSERT INTO EXT.TB_ASISTENCIA_ITX_HIS (ID_SUCURSAL, ID_EMPLEADO, FECHA_LECTURA, TIPO_LECTURA, TURNO, FECHA_CARGA) 
    SELECT TO_INT(ID_SUCURSAL), ID_EMPLEADO, TO_DATE(FECHA_LECTURA, 'MM/DD/YYYY'), TIPO_LECTURA, TURNO, TO_DATE(CURRENT_DATE)
    FROM EXT.TB_ASISTENCIA_ITX_TMP
    WHERE 1=1
    AND ACCION = 'INSERTAR';
 
-- Update Asistencia
UPDATE EXT.TB_ASISTENCIA_WKF
SET ASISTENCIA_ITX = true
WHERE EXISTS (
    SELECT 1
    FROM EXT.TB_ASISTENCIA_ITX_TMP
    WHERE TO_INT(EXT.TB_ASISTENCIA_ITX_TMP.ID_SUCURSAL) = EXT.TB_ASISTENCIA_WKF.ID_SUCURSAL
    AND EXT.TB_ASISTENCIA_ITX_TMP.ID_EMPLEADO = EXT.TB_ASISTENCIA_WKF.ID_EMPLEADO
    AND TO_DATE(EXT.TB_ASISTENCIA_ITX_TMP.FECHA_LECTURA, 'MM/DD/YYYY') = EXT.TB_ASISTENCIA_WKF.FECHA_ASISTENCIA
);
 
END