CREATE PROCEDURE EXT.SP_ACT_COMPLEMENTO_INDV (i INT, j INT, k DATE)
LANGUAGE SQLSCRIPT
SQL SECURITY INVOKER
DEFAULT SCHEMA EXT
AS
BEGIN
--i = SUCURSAL j = MESA
	DECLARE lv_NUM_EMPL_TRUE INT;
	DECLARE lv_PORC_PART_FALSE DECIMAL(10,5);
	DECLARE lv_PORC_PART_FALSE2 DECIMAL(10,5);
	DECLARE lv_SUCURSAL INT = 28;
	DECLARE lv_MESA INT = 5;
	DECLARE lv_FECHA DATE = :k;
	DECLARE lv_CONTADOR INT = 1;
	DECLARE lv_CONTADOR_FALSE INT = 1;
	DECLARE lv_CONT_MAX INT;
	DECLARE lv_NUM_EMPL_FALSE INT;
	DECLARE lv_PORC_PART_AUX INT;
	DECLARE lv_CONTADOR_SUCURSAL_INIT INT = 1;
	DECLARE lv_CONTADOR_MESA_INIT INT = 1;
	DECLARE lv_CONTADOR_SUCURSAL INT;
	DECLARE lv_CONTADOR_MESA INT;
	DECLARE lv_PUESTO INT;
	DECLARE lv_PORCENTAJE INT;
	DECLARE lv_SUMA_PORC DECIMAL(10,5);
	DECLARE lv_DIFF_PORC DECIMAL(10,5);
	DECLARE lv_SUMA_ASTNC DECIMAL(10,5);
	-- DECLARE i INT = 675;
	-- DECLARE j INT = 2;
			
			SELECT SUM(PORCENTAJE_PARTICIPACION_EMPLEADO)
			INTO lv_SUMA_ASTNC DEFAULT NULL
			FROM EXT.TB_ASISTENCIA_WKF
			WHERE ID_SUCURSAL = :i
			AND ID_MESA_REAL = :j
			AND ESTATUS_TRANS IN ('0', '2', '4')
			AND FECHA_ASISTENCIA = :lv_FECHA
			AND ASISTENCIA_ITX = TRUE;
			
			IF (lv_SUMA_ASTNC < 100) THEN
				
				SELECT 100 - SUM(PORCENTAJE_PARTICIPACION_EMPLEADO)
				INTO lv_SUMA_PORC DEFAULT NULL
				FROM EXT.TB_ASISTENCIA_WKF
				WHERE ID_SUCURSAL = :i
				AND ID_MESA_REAL = :j
				AND ESTATUS_TRANS IN ('0', '2', '4')
				AND FECHA_ASISTENCIA = :lv_FECHA
				AND ASISTENCIA_ITX = TRUE;
			
				SELECT F_NUMERO_EMPLEADOS_TRUE(i, j, lv_FECHA)
				INTO lv_NUM_EMPL_TRUE
				FROM DUMMY;
				
				UPDATE EXT.TB_ASISTENCIA_WKF
				SET PORCENTAJE_PARTICIPACION_EMPLEADO = TO_DECIMAL(PORCENTAJE_PARTICIPACION_EMPLEADO + (lv_SUMA_PORC/lv_NUM_EMPL_TRUE),10,5) -- (20 / 2)
				WHERE ID_SUCURSAL = i
				AND ID_MESA_REAL = j
				AND ESTATUS_TRANS IN ('0', '2', '4')
				AND ASISTENCIA_ITX = TRUE
				AND FECHA_ASISTENCIA = lv_FECHA;
				
			ELSE IF (lv_SUMA_ASTNC > 100) THEN
			
				SELECT SUM(PORCENTAJE_PARTICIPACION_EMPLEADO) - 100
				INTO lv_SUMA_PORC DEFAULT NULL
				FROM EXT.TB_ASISTENCIA_WKF
				WHERE ID_SUCURSAL = :i
				AND ID_MESA_REAL = :j
				AND ESTATUS_TRANS IN ('0', '2', '4')
				AND FECHA_ASISTENCIA = :lv_FECHA
				AND ASISTENCIA_ITX = TRUE;
			
				SELECT F_NUMERO_EMPLEADOS_TRUE(i, j, lv_FECHA)
				INTO lv_NUM_EMPL_TRUE
				FROM DUMMY;
				
				UPDATE EXT.TB_ASISTENCIA_WKF
				SET PORCENTAJE_PARTICIPACION_EMPLEADO = TO_DECIMAL(PORCENTAJE_PARTICIPACION_EMPLEADO - (lv_SUMA_PORC/lv_NUM_EMPL_TRUE),10,5) -- (20 / 2)
				WHERE ID_SUCURSAL = i
				AND ID_MESA_REAL = j
				AND ESTATUS_TRANS IN ('0', '2', '4')
				AND ASISTENCIA_ITX = TRUE
				AND FECHA_ASISTENCIA = lv_FECHA;
				
				END IF;
			END IF;
			
		UPDATE EXT.TB_ASISTENCIA_WKF
		SET PORCENTAJE_PARTICIPACION_EMPLEADO = 0
		WHERE ID_SUCURSAL = :i
		AND ID_MESA_REAL = :j
		AND ASISTENCIA_ITX = FALSE
		AND ESTATUS_TRANS IN ('0', '1', '2', '3', '4')
		AND FECHA_ASISTENCIA = :lv_FECHA;
END