CREATE PROCEDURE EXT.SP_ACT_VACANTES ()
LANGUAGE SQLSCRIPT
SQL SECURITY INVOKER
DEFAULT SCHEMA EXT
AS
BEGIN

	DECLARE lv_NUM_EMPL_TRUE INT;
	DECLARE lv_PORC_PART_FALSE DECIMAL(10,5);
	DECLARE lv_PORC_PART_FALSE2 DECIMAL(10,5);
	DECLARE lv_SUCURSAL INT = 28;
	DECLARE lv_MESA INT = 5;
	DECLARE lv_FECHA DATE = CURRENT_DATE;
	DECLARE lv_CONTADOR INT = 1;
	DECLARE lv_CONTADOR_FALSE INT = 1;
	DECLARE lv_CONT_MAX INT;
	DECLARE lv_NUM_EMPL_FALSE INT;
	DECLARE lv_PORC_PART_AUX INT;
	DECLARE lv_CONTADOR_SUCURSAL_INIT INT = 1;
	DECLARE lv_CONTADOR_MESA_INIT INT = 1;
	DECLARE lv_CONTADOR_SUCURSAL INT;
	DECLARE lv_CONTADOR_MESA INT;
	DECLARE lv_PUESTO INT;
	DECLARE lv_PORCENTAJE INT;
	DECLARE lv_MAX_SUCURSAL INT;
	DECLARE lv_MIN_SUCURSAL INT;
	DECLARE i INT;
	DECLARE j INT;

	SELECT MAX(ID_SUCURSAL)
	INTO lv_MAX_SUCURSAL DEFAULT NULL
	FROM EXT.TB_SUCURSAL_WKF;
	
	--RANGO DE SUCURSALES PARA CICLO
	SELECT MIN(ID_SUCURSAL)
	INTO lv_MIN_SUCURSAL DEFAULT NULL
	FROM EXT.TB_SUCURSAL_WKF;
	
		FOR i IN lv_MIN_SUCURSAL .. lv_MAX_SUCURSAL DO 
			FOR j IN 1 .. 6 DO
			
			SELECT COUNT(*)
			INTO lv_CONT_MAX DEFAULT NULL
			FROM EXT.TB_ASISTENCIA_TEST
			WHERE 1=1
			AND PORCENTAJE_PARTICIPACION_EMPLEADO != 0
			AND FECHA_ASISTENCIA = lv_FECHA; 
			
				IF lv_CONT_MAX IS NOT NULL THEN
				--GENERA EL NUMERO DE EMPLEADOS EN TRUE PARA DIVIDIR EL PORCENTAJE POR EMPLEADO
				
					
					SELECT COUNT(*)
					INTO lv_PUESTO DEFAULT NULL
					FROM (SELECT PORC.ID_CVE_CARGO AS PUESTO
					FROM EXT.TB_PORCPARTICIPACION_WKF PORC
					LEFT JOIN EXT.TB_SUCMESAEMPL_WKF SUC ON PORC.ID_CVE_CARGO  =  SUC.ID_CARGO 
					WHERE 1=1
					AND PORC.ID_SUCURSAL = i
					AND PORC.ID_MESA = j
					AND PORC.PORCENTAJE_PART_CARGO != 0
					EXCEPT
					SELECT SUC.ID_CARGO AS PUESTO 
					FROM EXT.TB_SUCMESAEMPL_WKF SUC
					WHERE  1=1
					AND SUC.ID_SUCURSAL = i
					AND SUC.ID_MESA = j);
				
					IF lv_PUESTO >= 1 THEN
						--FUNCION PARA OBTENER EL NUMERO DE EMPLEADOS A DIVIDIR
						SELECT F_NUMERO_EMPLEADOS_TRUE(i, j, lv_FECHA)
						INTO lv_NUM_EMPL_TRUE
						FROM DUMMY;
					
						--IDENTIFICA LAS DIFERENCIAS ENTRE CARGOS PARA OBTENER EL PORCENTAJE DE LA VACANTE
						SELECT TO_DECIMAL(SUM(PORCENTAJE_PART_CARGO) / 1,10,5) AS RESULTADO
						INTO lv_PORC_PART_FALSE DEFAULT NULL
						FROM EXT.TB_PORCPARTICIPACION_WKF
						WHERE ID_CVE_CARGO IN (SELECT PORC.ID_CVE_CARGO AS PUESTO
						FROM EXT.TB_PORCPARTICIPACION_WKF PORC
						LEFT JOIN EXT.TB_SUCMESAEMPL_WKF SUC ON PORC.ID_CVE_CARGO  =  SUC.ID_CARGO 
						WHERE 1=1
						AND PORC.ID_SUCURSAL = i
						AND PORC.ID_MESA = j
						AND PORC.PORCENTAJE_PART_CARGO != 0
						EXCEPT
						SELECT SUC.ID_CARGO AS PUESTO 
						FROM EXT.TB_SUCMESAEMPL_WKF SUC
						WHERE  1=1
						AND SUC.ID_SUCURSAL = i
						AND SUC.ID_MESA = j)
						AND ID_SUCURSAL = i
						AND ID_MESA =j;
						
						--ACTUALIZA EL PORCENTAJE EN LA TABLA DE ASISTENCIA PARA LOS EMPLEADOS EN TRUE
						UPDATE EXT.TB_ASISTENCIA_TEST
						SET PORCENTAJE_PARTICIPACION_EMPLEADO = TO_DECIMAL(PORCENTAJE_PARTICIPACION_EMPLEADO + (lv_PORC_PART_FALSE/lv_NUM_EMPL_TRUE),10,5) -- (20 / 2)
						WHERE ID_SUCURSAL = i
						AND ID_MESA_REAL = j
						AND ASISTENCIA_ITX = TRUE
						AND FECHA_ASISTENCIA = lv_FECHA;
	
					END IF;
				END IF;
			END FOR;
		END FOR;

END