CREATE PROCEDURE EXT.SP_ASIST_EXT (SUCURSAL INT, FECHA DATE)
LANGUAGE SQLSCRIPT
SQL SECURITY INVOKER
DEFAULT SCHEMA EXT
AS
BEGIN
 
-- DELETE
DELETE FROM EXT.TB_ASISTENCIA_WKF
WHERE ID_SUCURSAL = :SUCURSAL
AND FECHA_ASISTENCIA = :FECHA;
 
-- PLANTILLA BASE
-- REMOVE C480
INSERT INTO EXT.TB_ASISTENCIA_WKF (ID_SUCURSAL, ID_EMPLEADO, FECHA_ASISTENCIA, ESTATUS_TRANS, ID_CVE_EMPRESA, ID_MESA_ORIGINAL, ID_MESA_REAL, ID_CVE_CARGO, ID_CVE_CARGO_REAL, PORCENTAJE_PARTICIPACION_EMPLEADO, ASISTENCIA_ITX, DESCANSO, FECHA_CREACION, FECHA_MODIFICACION, USUARIO_CREACION, USUARIO_MODIFICACION)
SELECT DISTINCT PORC.ID_SUCURSAL, IFNULL(MP.ID_EMPLEADO, PORC.ID_SUCURSAL||PORC.ID_MESA||PORC.ID_CVE_CARGO||TO_INT(PORC.PORCENTAJE_PART_CARGO)), :FECHA, TO_VARCHAR(0), 'SO004', PORC.ID_MESA, PORC.ID_MESA, PORC.ID_CVE_CARGO, PORC.ID_CVE_CARGO, PORC.PORCENTAJE_PART_CARGO, TO_BOOLEAN('0'), TO_BOOLEAN('0'), CURRENT_DATE, CURRENT_DATE, 'SYSTEM', 'SYSTEM'
FROM (
		SELECT DISTINCT REF.GENERICATTRIBUTE1 ID_SUCURSAL, REF.NAME ID_EMPLEADO, :FECHA FECHA_ASISTENCIA, TO_VARCHAR(0) ESTATUS_TRANS, 'SO004' CVE_EMPRESA, PP.ID_MESA ID_MESA_ORIGINAL, PP.ID_MESA ID_MESA_REAL, REF.GENERICATTRIBUTE3 ID_CVE_CARGO, REF.GENERICATTRIBUTE3 ID_CVE_CARGO_REAL, PP.PORCENTAJE_PART_CARGO PORC, TO_BOOLEAN('0') ASISTENCIA_ITX, TO_BOOLEAN('0') DECORADO, CURRENT_DATE FECHA_CREACION, CURRENT_DATE FECHA_MODIFICACION, 'SYSTEM' USUARIO_CREACION, 'SYSTEM' USUARIO_MODIFICACION
	FROM (
		SELECT *
		FROM TCMP.CS_POSITION
		WHERE REMOVEDATE = '2200-01-01'
	) REF
	-- JOIN
	INNER JOIN EXT.TB_PORCPARTICIPACION_WKF PP
	ON REF.GENERICATTRIBUTE3 = PP.ID_CVE_CARGO
		AND REF.GENERICATTRIBUTE1 = PP.ID_SUCURSAL
		AND PP.ID_SUCURSAL = REF.GENERICATTRIBUTE1
	--WHERE
	WHERE REF.EFFECTIVESTARTDATE <= :FECHA
	AND :FECHA < REF.EFFECTIVEENDDATE
	AND REF.PAYEESEQ IS NOT NULL
	-- AND REF.GENERICATTRIBUTE1 NOT IN ('C480')
	AND REF.GENERICATTRIBUTE1 = TO_VARCHAR(:SUCURSAL)
) MP
RIGHT JOIN EXT.TB_PORCPARTICIPACION_WKF PORC
ON MP.ID_SUCURSAL = PORC.ID_SUCURSAL
AND MP.ID_MESA_ORIGINAL = PORC.ID_MESA
AND MP.ID_CVE_CARGO = PORC.ID_CVE_CARGO
WHERE PORC.ID_SUCURSAL = :SUCURSAL;
 
-- CARGA ASISTENCIA
UPDATE EXT.TB_ASISTENCIA_WKF
SET ASISTENCIA_ITX = TRUE
FROM EXT.TB_ASISTENCIA_WKF, EXT.TB_ASISTENCIA_ITX_HIS
WHERE EXT.TB_ASISTENCIA_WKF.ID_SUCURSAL = EXT.TB_ASISTENCIA_ITX_HIS.ID_SUCURSAL
AND EXT.TB_ASISTENCIA_WKF.ID_EMPLEADO = EXT.TB_ASISTENCIA_ITX_HIS.ID_EMPLEADO
AND EXT.TB_ASISTENCIA_WKF.FECHA_ASISTENCIA = EXT.TB_ASISTENCIA_ITX_HIS.FECHA_LECTURA
AND EXT.TB_ASISTENCIA_WKF.FECHA_ASISTENCIA = :FECHA
AND EXT.TB_ASISTENCIA_ITX_HIS.FECHA_LECTURA = :FECHA
AND EXT.TB_ASISTENCIA_WKF.ID_SUCURSAL = :SUCURSAL
AND EXT.TB_ASISTENCIA_ITX_HIS.ID_SUCURSAL = :SUCURSAL;
 
-- DESCANSO
UPDATE EXT.TB_ASISTENCIA_WKF
SET DESCANSO = TRUE
FROM EXT.TB_ASISTENCIA_WKF, EXT.TB_DESCANSO_WKF
WHERE EXT.TB_ASISTENCIA_WKF.ID_SUCURSAL = EXT.TB_DESCANSO_WKF.ID_SUCURSAL
AND EXT.TB_ASISTENCIA_WKF.ID_EMPLEADO = TO_VARCHAR(EXT.TB_DESCANSO_WKF.ID_NUM_EMPL)
AND EXT.TB_ASISTENCIA_WKF.FECHA_ASISTENCIA = EXT.TB_DESCANSO_WKF.ID_FEC_DESCANSO
AND EXT.TB_ASISTENCIA_WKF.FECHA_ASISTENCIA = :FECHA
AND EXT.TB_DESCANSO_WKF.ID_FEC_DESCANSO = :FECHA
AND EXT.TB_ASISTENCIA_WKF.ID_SUCURSAL = :SUCURSAL
AND EXT.TB_DESCANSO_WKF.ID_SUCURSAL = :SUCURSAL;
END