CREATE PROCEDURE EXT.SP_CANCELAINCIDENCIA_ITX_NEW (OUT FILENAME VARCHAR(255), IN pPlRunSeq BIGINT)
LANGUAGE SQLSCRIPT
SQL SECURITY INVOKER
DEFAULT SCHEMA EXT
AS
BEGIN
	DECLARE vPeriodSeq BIGINT;
	DECLARE vFechaArchivo VARCHAR(50);
	DECLARE LV_IDTRANSACCION BIGINT;
	DECLARE LV_IDTRANS VARCHAR(255);
	DECLARE LV_NOMBRE VARCHAR(255);
	DECLARE LV_TOTAL_REGISTROS INTEGER;
	DECLARE LV_USER VARCHAR(127);
	DECLARE LV_CORREO VARCHAR(127);
	DECLARE LV_FECHA_CANCELACION TIMESTAMP;
	DECLARE LV_MAIN_PERIOD VARCHAR(127);
	DECLARE LV_LASTPIPE BIGINT;
	-- Plan
	DECLARE LV_DATE_PERIODSEQ DATE;
	DECLARE LV_PER_STARTDATE DATE;
	DECLARE LV_PER_ENDDATE DATE;
	
	-- PERIODO y USUARIO
	SELECT PERIODSEQ, USERID
	INTO vPeriodSeq, LV_USER
	FROM TCMP.CS_PlRUN
	WHERE PIPELINERUNSEQ = :pPlRunSeq;
	
	-- LAST PERIOD
	SELECT MAX(PIPELINERUNSEQ)
	INTO LV_LASTPIPE DEFAULT NULL
	FROM TCMP.CS_DEPOSIT
	WHERE PERIODSEQ = :vPeriodSeq;
	
	-- FECHAS	
	SELECT TO_CHAR(CURRENT_TIMESTAMP, 'YYYYMMDD_HH24MISS'), CURRENT_TIMESTAMP
	INTO vFechaArchivo, LV_FECHA_CANCELACION
	FROM DUMMY;
	
	-- BORRAR REGISTROS ANTERIORES		
	DELETE FROM EXT.TB_CANCINC_AUX_NEW
	WHERE 1 = 1;
	
	DELETE FROM EXT.TB_CANCINC_ITX_NEW
	WHERE 1 = 1;
	
	-- ID TRANSACCION
	SELECT MAX(ID_TRANSACCION)
	INTO LV_IDTRANSACCION
	FROM EXT.TB_IDTRANSACCION_ITX;
	
	-- TO FILENAME
	SELECT TO_VARCHAR(MAX(ID_TRANSACCION) + 1)
	INTO LV_IDTRANS
	FROM EXT.TB_IDTRANSACCION_ITX;
	
	-- PERIOD PIPELINE
	SELECT TO_VARCHAR(TO_DATE(ADD_DAYS(STARTDATE, -6)), 'YYYYMMDD')||'_'||TO_VARCHAR(TO_DATE(STARTDATE), 'YYYYMMDD')
	INTO LV_MAIN_PERIOD
	FROM TCMP.CS_PERIOD
	WHERE PERIODSEQ = :vPeriodSeq
	LIMIT 1;
	
	-- Plan
	-- Transform PERIODSEQ to DATE
	SELECT STARTDATE
	INTO LV_DATE_PERIODSEQ DEFAULT NULL
	FROM TCMP.CS_PERIOD
	WHERE PERIODSEQ = :vPeriodSeq
	AND REMOVEDATE = '2200-01-01';
	
	LV_NOMBRE = 'CANCELAINC_'||vFechaArchivo||'_'||LV_MAIN_PERIOD||'_'||LV_IDTRANS||'.txt';
	
	-- ID TRANSACCION NUEVA
	LV_IDTRANSACCION = LV_IDTRANSACCION + 1;

	-- INSERCIÓN DE REGISTROS
	INSERT INTO EXT.TB_CANCINC_AUX_NEW (ID_TRANSACCION, ID_EMPLEADO, CONCEPTO, PARAMDATE1, PARAMSTR1)
		SELECT DISTINCT LV_IDTRANSACCION AS ID_TRANSACCION, PS.NAME AS ID_EMPLEADO, DP.EARNINGCODEID AS CONCEPTO, TO_CHAR(PR.STARTDATE, 'YYYY-MM-DD') AS PARAMDATE1, ER.DESCRIPTION AS PARAMSTR1
		FROM TCMP.CS_DEPOSIT AS DP
		INNER JOIN TCMP.CS_POSITION AS PS
		ON DP.POSITIONSEQ = PS.RULEELEMENTOWNERSEQ
		INNER JOIN TCMP.CS_PERIOD AS PR
		ON DP.PERIODSEQ = PR.PERIODSEQ
		INNER JOIN TCMP.CS_EARNINGCODE AS ER
		ON DP.EARNINGCODEID = ER.EARNINGCODEID
		INNER JOIN EXT.TB_SUCACT_PRD SA
		ON TO_INT(PS.GENERICATTRIBUTE1) = SA.ID_SUCURSAL
		INNER JOIN EXT.TB_CARGOS_WKF CAR
		ON CAR.ID_CARGO = PS.GENERICATTRIBUTE3
		INNER JOIN EXT.TB_SUCURSAL_WKF SUC
		ON SUC.ID_TIPO_MESA = CAR.ID_TIPO_MESA
		AND SUC.ID_SUCURSAL = PS.GENERICATTRIBUTE1
		WHERE 1 = 1
		AND DP.PIPELINERUNSEQ = :LV_LASTPIPE
		AND DP.PERIODSEQ = :vPeriodSeq 
		AND DP.EARNINGCODEID IN ('P0139', 'P0162', 'P0161', 'P0163','P0167', 'P0168', 'P0177', 'P0316')
		AND PS.REMOVEDATE = '2200-01-01 00:00:00.000000000'
		-- AND PS.ISLAST = 1 -- QUIT
		AND PS.EFFECTIVESTARTDATE <= :LV_DATE_PERIODSEQ -- Validate vers
		AND :LV_DATE_PERIODSEQ < PS.EFFECTIVEENDDATE -- Validate vers
		AND EARNINGGROUPID IN ('COMISION_ROJA', 'COMISION_AZUL', 'COMISION_EXPRESS', 'COMISION_CITYCLUB')
		AND PR.REMOVEDATE = '2200-01-01 00:00:00.000000000'
		AND ER.REMOVEDATE = '2200-01-01 00:00:00.000000000'
		AND SA.ESTATUS = TRUE;
	
	-- CONTEO DE REGISTROS			
	SELECT COUNT(*)
	INTO LV_TOTAL_REGISTROS
	FROM EXT.TB_CANCINC_AUX_NEW
	WHERE 1 = 1;
			
	INSERT INTO EXT.TB_IDTRANSACCION_ITX VALUES(LV_IDTRANSACCION, LV_NOMBRE);
	
	-- INSERT
	INSERT INTO EXT.TB_CANCINC_ITX_NEW (ID_TRANSACCION, NOM_ARCHIVO, TOTAL_REGISTROS, ORIGEN, USUARIO, ID_EMPLEADO, CONCEPTO, PARAMDATE1, PARAMSTR1)
	SELECT ID_TRANSACCION, LV_NOMBRE, LV_TOTAL_REGISTROS, 'SAP_COMMISSIONS', LV_USER, ID_EMPLEADO, CONCEPTO, PARAMDATE1, PARAMSTR1
	FROM EXT.TB_CANCINC_AUX_NEW
	WHERE 1 = 1;
	
	FILENAME := :LV_NOMBRE;
	
END